### PR TITLE
Main Menu UI fix for OM2329-8

### PR DESCRIPTION
**Pull request by SJVswan**
#### Description
This PR implements the UI that was agreed upon during the 2/13 meeting. Background colors are added to the main menu screen to match our Figma prototype. The font is changed to sans-serif "Kanit" for readability. Lastly, a widget_test.dart error is resolved - pumpWidget now uses "MainScreen" rather than "MyApp" (which isn't a valid input for the function).

#### Screenshots (if appropriate):
image

#### Types of Changes
- [ ] New feature: This changes the UI from Flutter's default to one that matches the specifications agreed to during the 2/13 team meeting, effectively resolving the Main Menu UI polish task [OM2329-8](https://jib-2329.atlassian.net/browse/OM2329-8).

#### Notes
If we want to decide on a different font, we can always change it later. Depending on how future screens are implemented, we may have to do additional PRs to maintain consistency with the app UI. 

#### Checklist
- [x] Moved the task in Jira to 'In Review'
- [ ] Updated the Incremental Release Notes

### CODE REVIEW

**Comment by Alex-Laney** [comment]
Looks good. Do we want to leave the button and menu bar colors as the default blue, change it to the grey we had in the Figma, or is there some other color that you think would look better?

**Comment by SJVswan** [comment]
Since our background colors are changing, we would have to decide if we want to use a universal color scheme for our button and menu bar or have a unique color scheme for each screen. I think we can leave it as default blue for now and address it at our next meeting and/or sprint

**Comment by Alex-Laney** [comment]
Additional UI work will be done post our meeting tomorrow, 2/17.

**Comment by SJVswan** [comment]
> Additional UI work will be done post our meeting tomorrow, 2/17.

Is there anything additional you want for this PR or is this good to go?

**Pull request merged**
